networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wordpress-volume:
    driver: local
    # driver-opts:
      # device: path
      # o: bind
      # type: none
  mariadb-volume:
    driver: local
    # driver-opts:
      # device: path
      # o: bind
      # type: none

services:
  nginx:
    build: ./requirements/nginx
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress-volume:/var/www/html
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    networks:
      - inception
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_HOST=${DB_HOST}
      - WP_ADMIN_NAME=${WP_ADMIN_NAME}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    depends_on:
      - mariadb
    volumes:
      - wordpress-volume:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    restart: always
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    volumes:
      - mariadb-volume:/var/lib/mysql
