networks:
  inception:
    name: inception

volumes:
  wordpress-volume:
    driver: local
    # driver-opts:
    #   type: none
  mariadb-volume:
    driver: local
    # driver-opts:
    #   type: none

services:
  nginx:
    build: ./requirements/nginx
    restart: always
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress-volume:/var/www/html
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    expose:
      - 9000
    restart: always
    networks:
      - inception
    environment:
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_USERNAME=${WP_USERNAME}
      - WP_DB_PASSWORD=${WP_DB_PASSWORD}
      - WP_DB_HOST=${WP_DB_HOST}
      - WP_ADMIN_NAME=${WP_ADMIN_NAME}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    depends_on:
      - mariadb
    volumes:
      - wordpress-volume:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    restart: always
    container_name: mariadb
    expose:
      - 3306
    networks:
      - inception
    environment:
      - MYSQL_ROOT_PASSWORD=${WP_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WP_DB_NAME}
      - MYSQL_USER=${WP_USERNAME}
      - MYSQL_PASSWORD=${WP_DB_PASSWORD}
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_USERNAME=${WP_USERNAME}
      - WP_DB_PASSWORD=${WP_DB_PASSWORD}
      - WP_DB_HOST=${WP_DB_HOST}
      - WP_DB_ROOT_PASSWORD=${WP_DB_ROOT_PASSWORD}
    volumes:
      - mariadb-volume:/var/lib/mysql
