networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/cwenz/data/wordpress-volume
      o: bind
      type: none
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/cwenz/data/mariadb-volume
      o: bind
      type: none

services:
  nginx:
    build: ./requirements/nginx
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
 #       condition: service_healthy
    volumes:
      - wordpress-volume:/var/www/html
    healthcheck:
      test: ["CMD", "curl", "-k", " https://cwenz.42.fr"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    networks:
      - inception
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_HOST=${DB_HOST}
      - WP_ADMIN_NAME=${WP_ADMIN_NAME}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    depends_on:
      - mariadb
 #       condition: service_healthy
    volumes:
      - wordpress-volume:/var/www/html
#    healthcheck:
#      test: ["CMD", "wp", "core", "is-installed"]
#      interval: 5s
#      timeout: 5s
#      retries: 100

  mariadb:
    build: ./requirements/mariadb
    restart: always
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    volumes:
      - mariadb-volume:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "cwenz.42.fr"]
#      interval: 5s
#      timeout: 5s
#      retries: 100
