version: '3.8'

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
